---
apiVersion: v1
kind: Namespace
metadata:
  name: dummy-ns
---
apiVersion: bpf.sh/v1alpha1
kind: BPF
metadata:
  name: dummy-bpf
  namespace: dummy-ns
spec:
  program:
    valueFrom:
      configMapKeyRef:
        name: dummy-config
        key: dummy.o
---
apiVersion: v1
binaryData:
  dummy.o: f0VMRgIBAQAAAAAAAAAAAAEA9wABAAAAAAAAAAAAAAAAAAAAAAAAANADAAAAAAAAAAAAAEAAAAAAAEAACwABAIUAAAAOAAAAYwr8/wAAAAC3AQAAAQAAAGMa+P8AAAAAv6IAAAAAAAAHAgAA/P///xgBAAAAAAAAAAAAAAAAAACFAAAAAQAAAL+jAAAAAAAABwMAAPj///8VAAQAAAAAAGEBAAAAAAAABwEAAAEAAABjEAAAAAAAAL8DAAAAAAAAv6IAAAAAAAAHAgAA/P///xgBAAAAAAAAAAAAAAAAAAC3BAAAAAAAAIUAAAACAAAAtwAAAAAAAACVAAAAAAAAAAEAAAAEAAAABAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHUEwA/v///xAAAAAAAAAAAXpSAAh8CwEMAAAAGAAAABgAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAMAgAAAAAAAAAAAAAAAAAAAAAAAAAADAAMAAAAAAAAAAAAAAAAAAAAAAHkAAAAQAAYAAAAAAAAAAAAAAAAAAAAAAA0AAAAQAAcAAAAAAAAAAAAAAAAAAAAAAAEAAAAQAAUAAAAAAAAAAAAAAAAAAAAAABYAAAAQAAMAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAQAAAAUAAACQAAAAAAAAAAEAAAAFAAAAHAAAAAAAAAABAAAAAgAAAABkdW1teQAudGV4dABfdmVyc2lvbgB0cmFjZXBvaW50X19zeXNjYWxsc19fc3lzX2VudGVyX3dyaXRlAG1hcHMvc3lzX2VudGVyX3dyaXRlAC5yZWx0cmFjZXBvaW50L3N5c2NhbGxzL3N5c19lbnRlcl93cml0ZQBfbGljZW5zZQAucmVsLmVoX2ZyYW1lAC5zdHJ0YWIALnN5bXRhYgBMQkIwXzIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAoAwAAAAAAAKcAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAABwAAAAEAAAAGAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAFUAAAABAAAABgAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAABRAAAACQAAAAAAAAAAAAAAAAAAAAAAAAD4AgAAAAAAACAAAAAAAAAACgAAAAMAAAAIAAAAAAAAABAAAAAAAAAAPAAAAAEAAAADAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAYAQAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAHoAAAABAAAAAwAAAAAAAAAAAAAAAAAAABgCAAAAAAAABAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAOAAAAAQAAAAMAAAAAAAAAAAAAAAAAAAAcAgAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAhgAAAAEAAAACAAAAAAAAAAAAAAAAAAAAIAIAAAAAAAAwAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAIIAAAAJAAAAAAAAAAAAAAAAAAAAAAAAABgDAAAAAAAAEAAAAAAAAAAKAAAACAAAAAgAAAAAAAAAEAAAAAAAAACYAAAAAgAAAAAAAAAAAAAAAAAAAAAAAABQAgAAAAAAAKgAAAAAAAAAAQAAAAMAAAAIAAAAAAAAABgAAAAAAAAA
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dummy-config
  namespace: dummy-ns
